name: 'Test Package'
inputs:
  container:
    description: "bool"
  system:
    description: "string (ubuntu/debian/.../macos/windows)"
  os:
    description: "string (linux/macos/windows)"
  cmake_test_args:
    description: "string"
  test_launcher:
    description: "string"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          doc/examples/special
        sparse-checkout-cone-mode: false
    - uses: actions/download-artifact@v4
      with:
        name: packages-${{ inputs.os }}
        path: packages
    - name: Relocate test sources
      shell: bash
      run: |
        mv doc/examples/special/* .
        rm -rf doc
        ls *

    - name: Install DEB
      shell: bash
      run: |
        ${{ !inputs.container && 'sudo' || '' }} apt-get install -y ./packages/OGDF-*-Linux.deb
      if: ${{ inputs.system == 'debian' || inputs.system == 'ubuntu' }}
    - name: Install RPM
      shell: bash
      run: |
        dnf install -y ./packages/OGDF-*-Linux.rpm
      if: ${{ inputs.system == 'fedora' }}
    - name: Install SH
      shell: bash
      run: |
        chmod +x ./packages/OGDF-*-Linux.sh
        ./packages/OGDF-*-Linux.sh --skip-license
      if: ${{ inputs.system == 'archlinux' }}
    - name: Install NSIS (Windows)
      shell: pwsh
      run: |
        ./packages/OGDF-*-Windows.exe
      if: ${{ inputs.system == 'windows' }}
    - name: Install PKG (MacOS)
      shell: bash
      run: |
        sudo installer -pkg ./packages/OGDF-*-Darwin.pkg -target /
      if: ${{ inputs.system == 'macos' }}

    - name: Check search paths #debug
      shell: bash
      run: |
        # https://stackoverflow.com/q/9922949
        echo "::group::ld"
        ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012
        echo "::endgroup::"
        echo "::group::gcc"
        gcc -print-search-dirs | sed '/^lib/b 1;d;:1;s,/[^/.][^/]*/\.\./,/,;t 1;s,:[^=]*=,:;,;s,;,;  ,g;s/;  //g;s/:/\n  /g'
        echo "::endgroup::"
        echo "::group::ldconfig"
        ldconfig -v || echo "error $?"
        echo "::endgroup::"
        echo "::group::ldconfig2"
        ldconfig -v 2>/dev/null | grep -v ^$'\t'  || echo "error $?"
        echo "::endgroup::"
      if: ${{ inputs.os == 'linux' }}

    - name: Test installed build results
      shell: bash
      if: ${{ inputs.system != 'archlinux' }}
      run: |
        mkdir build-test && cd build-test
        export CCACHE_BASEDIR="$(pwd)"
        set -x
        cmake .. --debug-find ${{ inputs.cmake_test_args }}

        cmake --build . --config Debug
        cmake --build . --config Release
        ls -al *
        
        ${{ inputs.os == 'linux' && 'ldd Release/check-build-mode; readelf -d Release/check-build-mode' || '' }} #debug
        ${{ inputs.os == 'linux' && 'ldd Debug/check-build-mode; readelf -d Debug/check-build-mode' || '' }} #debug
        
        ${{ inputs.test_launcher }}Release/check-build-mode${{ inputs.system == 'windows' && '.exe' || '' }}
        ${{ inputs.test_launcher }}Debug/check-build-mode${{ inputs.system == 'windows' && '.exe' || '' }}

    - name: Test installed build results (arch)
      shell: bash
      if: ${{ inputs.system == 'archlinux' }}
      run: |
        mkdir build-test && cd build-test
        export CCACHE_BASEDIR="$(pwd)"
        export CMAKE_LIBRARY_PATH="/usr/local/share/"
        set -x
        cmake .. --debug-find ${{ inputs.cmake_test_args }}

        cmake --build . --config Debug && exit 99
        cmake --build . --config Release && exit 99
        
        pacman -Sy --noconfirm libunwind
        cmake --build . --config Debug
        cmake --build . --config Release
        ls -al *
        
        ldd Release/check-build-mode; readelf -d Release/check-build-mode
        ldd Debug/check-build-mode; readelf -d Debug/check-build-mode
        
        ${{ inputs.test_launcher }}Release/check-build-mode
        ${{ inputs.test_launcher }}Debug/check-build-mode
