OUTPUTS = \
	energy-based/main \
	energy-based/multilevelmixer/fast/main \
	energy-based/multilevelmixer/nice/main \
	energy-based/multilevelmixer/no-twist/main \
	orthogonal/main \
	hierarchical-ranking/main \
	hierarchical/main \
	hypergraph/main

include ../Makefile.inc
