name: Check, Build and Test

on:
  push:
  pull_request:
    branches: [master]
  release:
    types: [published]

# # Debug setup:
# env:
#   OGDF_UTILS_PREQUEL: "set -x"
#   CCACHE_DEBUG: 1
#   CCACHE_DEBUGDIR: ${{ github.workspace }}/ccache-debug

jobs:
  style:
    name: "Check code style"
    runs-on: ubuntu-latest
    container: docker.io/ogdf/clang:15
    steps:
      - name: "Add workspace as a safe directory in containers"
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - run: util/style/test_clang_format.sh
      - run: util/style/test_eols.sh
      - run: util/style/test_number_newlines.sh
      - run: util/style/test_line_length.sh
      - run: util/style/test_tabs.sh
      - run: util/style/test_macros.sh
      - run: util/style/test_license.sh
      - run: util/style/test_no_typedefs.sh
      - run: util/style/test_no_enums.sh
      - run: util/style/test_indent_comments.sh

  dirs:
    name: "Check directory structure"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test directory structure
        run: util/test_directory_structure.sh

  docs:
    name: "Check Doxygen"
    runs-on: ubuntu-latest
    container: docker.io/ogdf/clang:15
    steps:
      - uses: actions/checkout@v4
      - run: util/test_doxygen.sh

  self-sufficiency:
    name: "Test self-sufficiency"
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -v"
    steps:
      - uses: actions/checkout@v4
      - name: "Register ccache cleanup post-action"
        uses: ./.github/actions/prune-cache
        with:
          ref: ${{ github.ref }}
          prefix: ccache-${{ github.job }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set-up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
      - name: Test self-sufficiency
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          util/test_self-sufficiency.sh
      - uses: actions/upload-artifact@v4
        name: Upload ccache debug info
        if: ${{ env.CCACHE_DEBUG == 1 }}
        with:
          name: ${{ github.job }}
          path: ${{ github.workspace }}/ccache-debug

  sonar:
    name: "Static Analysis"
    if: |
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    container: docker.io/ogdf/clang:15
    needs: [style, dirs, self-sufficiency, docs]
    env:
      CCACHE_COMPILERCHECK: "%compiler% -v"
    steps:
      - name: "Add workspace as a safe directory in containers"
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history for blame info
      - name: Install sonar-scanner
        uses: SonarSource/sonarcloud-github-c-cpp@v2
      - name: Set-up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
      - name: Set-up clang-tidy cache
        uses: actions/cache@v4
        with:
          path: .ctcache
          key: clang-tidy-cache
      - name: Run analysis
        env:
          CTCACHE_DIR: .ctcache
          # CTCACHE_DUMP: ${{ env.CCACHE_DEBUG }} # defining the var is enough to enable
        run: |
          util/sonar.sh -DOGDF_ARCH=haswell -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          find .ctcache -mtime +7 -delete
          cat sonar/clang-tidy.txt | python3 -m clang_tidy_converter sq > sonar/clang-tidy.json
        shell: bash
      - name: Report unused files
        run: cat sonar/unused-headers.txt
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner
      - name: Store logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sonar
          path: sonar/
      - uses: actions/upload-artifact@v4
        name: Upload ccache debug info
        if: ${{ env.CCACHE_DEBUG == 1 }}
        with:
          name: ${{ github.job }}
          path: ${{ github.workspace }}/ccache-debug
